/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.istidat.ec1_bances_leonardo;

import java.awt.event.ActionEvent;

/**
 *
 * @author lbanc
 */
public class frmEjercicio04 extends javax.swing.JFrame {

    /**
     * Creates new form frmEjercicio04
     */
    
    double importeTotal1 = 0, importeTotal2 = 0, importeTotal3 = 0, importeTotal4 = 0;
    int numeroLicencia1 = 0, numeroLicencia2 = 0, numeroLicencia3 = 0, numeroLicencia4 = 0;
    int numeroVenta1 = 0, numeroVenta2 = 0, numeroVenta3 = 0, numeroVenta4 = 0;
    
    Double licencia0 = 0.0;
    Double licencia1 = 510.0;
    Double licencia2 = 1500.0;
    Double licencia3 = 3100.0;
    Double licencia4 = 4500.0;
    
    
    public frmEjercicio04() {
        initComponents();
        cargarItems();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        btnProcesar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultado1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtResultado2 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        cmbLicencia = new javax.swing.JComboBox<>();
        txtNumero = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnProcesar.setText("Procesar");
        btnProcesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcesarActionPerformed(evt);
            }
        });

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        txtResultado1.setColumns(20);
        txtResultado1.setRows(5);
        jScrollPane1.setViewportView(txtResultado1);

        txtResultado2.setColumns(20);
        txtResultado2.setRows(5);
        jScrollPane2.setViewportView(txtResultado2);

        jLabel1.setText("Tipo de Licencia:");

        jLabel2.setText("Número de Licencias");

        jLabel3.setText("Venta Actual");

        jLabel4.setText("Reporte Histórico");

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbLicencia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(81, 81, 81)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnProcesar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(btnCerrar)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cmbLicencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnProcesar)
                        .addGap(18, 18, 18)
                        .addComponent(btnBorrar)))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(3, 3, 3)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btnCerrar)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcesarActionPerformed
        // TODO add your handling code here:
        
        int licencia, numero;
        double totalPagar;

        licencia = getLicencia();
        numero = getNumero();

        totalPagar = calcular(licencia, numero);

        ventaActual(licencia, numero, totalPagar);
        reporteHistorico();
        actualizarHistorico(licencia, numero, totalPagar);
        
    }//GEN-LAST:event_btnProcesarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        // TODO add your handling code here:
        
        txtNumero.setText("");
        txtResultado1.setText("");
        txtResultado2.setText("");
        cmbLicencia.setSelectedIndex(0);
        txtNumero.requestFocus();
        
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        
        dispose();
        
    }//GEN-LAST:event_btnCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEjercicio04.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEjercicio04.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEjercicio04.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEjercicio04.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmEjercicio04().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnProcesar;
    private javax.swing.JComboBox<String> cmbLicencia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextArea txtResultado1;
    private javax.swing.JTextArea txtResultado2;
    // End of variables declaration//GEN-END:variables

    private void cargarItems() {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        
        cmbLicencia.addItem("Seleccionar");
        cmbLicencia.addItem("Cobre");
        cmbLicencia.addItem("Bronze");
        cmbLicencia.addItem("Silver");
        cmbLicencia.addItem("Gold");
        
    }

    private int getLicencia() {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        
        return cmbLicencia.getSelectedIndex();
        
    }

    private int getNumero() {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        
        return Integer.parseInt(txtNumero.getText());
        
    }

    private double calcular(int licencia, int numero) {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        
        switch (licencia){
            case 0:
                return licencia0 + 0;
            case 1:
                return licencia1 * numero;
            case 2:
                return licencia2 * numero;
            case 3:
                return licencia3 * numero;
            default:
                return licencia4 * numero;
        }
    }

    private void actualizarHistorico(int licencia, int numero, double totalPagar) {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody

        switch (licencia) {
            case 0:
                importeTotal1 += totalPagar;
                numeroLicencia1 += numero;
                numeroVenta1++;
                break;
            case 1:
                importeTotal2 += totalPagar;
                numeroLicencia2 += numero;
                numeroVenta2++;
                break;
            case 2:
                importeTotal3 += totalPagar;
                numeroLicencia3 += numero;
                numeroVenta3++;
                break;
            default:
                importeTotal4 += totalPagar;
                numeroLicencia4 += numero;
                numeroVenta4++;
        }
    }

    private void ventaActual(int licencia, int numero, double totalPagar) {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        
        String strLicencia = (String) cmbLicencia.getItemAt(licencia);
        txtResultado1.setText("");
        mostrar1("Tipo de Licencia       :" + strLicencia);
        mostrar1("Número de Licencias    :" + numero);
        mostrar1("Importe a pagar        :" + totalPagar);
        
    }

    private void mostrar1(String cad) {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        
          txtResultado1.append(cad + "\n");
        
    }

    private void reporteHistorico() {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        
        txtResultado2.setText("");
        mostrar2("Importe total recaudado");
        mostrar2(" Por licencias Cobre   : " + importeTotal1);
        mostrar2(" Por licencias Bronce  : " + importeTotal2);
        mostrar2(" Por licencias Silver  : " + importeTotal3);
        mostrar2(" Por licencias Gold    : " + importeTotal4);
        mostrar2("");
        mostrar2("Número de licencias vendidas");
        mostrar2(" Por licencias Cobre   : " + numeroLicencia1);
        mostrar2(" Por licencias Bronce  : " + numeroLicencia2);
        mostrar2(" Por licencias Silver  : " + numeroLicencia3);
        mostrar2(" Por licencias Gold    : " + numeroLicencia4);
        mostrar2("");
        mostrar2("Número de ventas efectuadas");
        mostrar2(" Por licencias Cobre   : " + numeroVenta1);
        mostrar2(" Por licencias Bronce  : " + numeroVenta2);
        mostrar2(" Por licencias Silver  : " + numeroVenta3);
        mostrar2(" Por licencias Gold    : " + numeroVenta4);
        mostrar2("");
        
    }

    private void mostrar2(String cad) {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        
          txtResultado2.append(cad + "\n");
        
    }
}
